apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: prometheus-telemetry
    app.kubernetes.io/instance: prometheus-telemetry
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: prometheus-telemetry
    app.kubernetes.io/part-of: openshift-monitoring
  name: system:prometheus-telemetry
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  nonResourceURLs:
  - /federate
  verbs:
  - get
