apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  instance:
    operator.prometheus.io/controller-id: openshift-monitoring/prometheus-operator
  labels:
    app.kubernetes.io/component: prometheus-telemetry
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: prometheus-telemetry
    app.kubernetes.io/part-of: openshift-monitoring
  name: telemetry
  namespace: openshift-monitoring
spec:
  additionalArgs:
  - name: scrape.timestamp-tolerance
    value: 15ms
  additionalScrapeConfigs:
    key: telemetry-scrape.yaml
    name: telemetry-scrape
  configMaps:
  - serving-certs-ca-bundle
  - kubelet-serving-ca-bundle
  - metrics-client-ca
  containers:
  - env:
    - name: HTTP_PROXY
      value: ""
    - name: HTTPS_PROXY
      value: ""
    - name: NO_PROXY
      value: ""
    name: prometheus
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /etc/pki/ca-trust/extracted/pem/
      name: prometheus-telemetry-trusted-ca-bundle
    - mountPath: /etc/tls/private
      name: secret-prometheus-telemetry-tls
    - mountPath: /etc/tls/client
      name: metrics-client-ca
      readOnly: true
  enableFeatures:
  - delayed-compaction
  listenLocal: true
  maximumStartupDurationSeconds: 3600
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: prometheus
          app.kubernetes.io/instance: telemetry
          app.kubernetes.io/name: prometheus
          app.kubernetes.io/part-of: openshift-monitoring
      namespaces:
      - openshift-monitoring
      topologyKey: kubernetes.io/hostname
  podMetadata:
    annotations:
      openshift.io/required-scc: nonroot
      target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
  priorityClassName: system-cluster-critical
  replicas: 1
  resources:
    requests:
      cpu: 70m
      memory: 1Gi
  scrapeClasses: []
  scrapeConfigNamespaceSelector: null
  scrapeConfigSelector: null
  secrets:
  - metrics-client-certs
  securityContext:
    fsGroup: 65534
    runAsNonRoot: true
    runAsUser: 65534
  serviceMonitorSelector:
    matchLabels:
      app.kubernetes.io/instance: telemetry
  volumes:
  - configMap:
      items:
      - key: ca-bundle.crt
        path: tls-ca-bundle.pem
      name: prometheus-telemetry-trusted-ca-bundle
    name: prometheus-telemetry-trusted-ca-bundle
  web:
    httpConfig:
      headers:
        contentSecurityPolicy: frame-ancestors 'none'
