- job_name: telemetry-scrape
  static_configs:
    - targets:
        - prometheus-k8s.openshift-monitoring.svc:9092
  metrics_path: /federate
  scrape_interval: 4m30s
  scheme: https
  tls_config:
    ca_file: /etc/serving-certs-ca-bundle/service-ca.crt
    key_file: /etc/tls/private/tls.key
    cert_file: /etc/tls/private/tls.crt
  params:
    'match[]':
      - '{__name__="count:up0"}'
